### ISSUE TITLE
Groups in vex

### ISSUE THREAD

**Issue by AminKhormaei** [kiryha/Houdini#3]
your guide to vex is awesome, I'm reading it now, could you plz explain groups in vex?.
BEST REGARDS

**Comment by kiryha** [comment]
Thank you, aminkhormaei!

https://github.com/kiryha/Houdini/wiki/vex-snippets#create-groups

**Comment by pixelpicnic** [comment]
Would you want to include the i@group_[group_name] =1; syntax?
not sure of that's outside the scope of this project ;)

**Comment by kiryha** [comment]
I think I have it there :)
// Alternative: i@group_high = 1
